package com.sallahli.utils;

public enum SortedItemName {

    PRODUCT, PRODUCT_SECTION,SPECIALITY,PRODUCT_CATEGORY,PARTNER_CATEGORY,BANNER,BANNER_EXTERNAL_ELEMENT,BANNER_REQUEST,OPTION_RELATION,GROUP_OPTION,OPTION
}


