package com.pro.model.Enum;

public enum INT_NOTIFICATION {
  CLIENT_ACCEPTED_ORDER,
  CLIENT_DELIVERED_ORDER,
  CLIENT_CANCELED_ORDER,
  DRIVER_PAYMENT,
  DRIVER_PAYMENT_PROBLEM,
  DRIVER_BREAK_DONE,
  SCHEDULED_ORDER,
  ORDER_WALLET_MINUS,
  ORDER_WALLET_EQUITY,
  ORDER_WALLET_PLUS,
  ORDER_STEP_DONE,
  WALLET_UPDATE,
  WALLET_BALANCE_INCREASED,
  DRIVER_OFFLINE,
  VOUCHER,
  VOUCHER_BEFORE_EXPIRY,
  DRIVER_ORDER_CANCELED,
  CLIENT_SCHEDULED_ORDER,
  ENTERPRISE_REVERT_INVOICE_PAYMENT,
  ENTERPRISE_INVOICE_CONFIRMED,
  NO_MANAGER_ORDER,
  ENTERPRISE_INVOICE_PAID,
  STATION_HAS_NO_DRIVER_CONNECTED;
  public final static String FILE_NAME = "notification";
}


